nve_md:
  test_data: null
  calculator_params:
    num_steps: 10000
    timestep: 1.0
    temperature: 300
phonon_mdr:
  test_data: /bohr/lambench-phonon-y7vk/v1/MDR_PBE_phonon
  calculator_params:
    distance: 0.01
inference_efficiency:
  test_data: /bohr/lambench-efficiency-rg7a/v3/efficiency
  calculator_params:
    warmup_ratio: 0.1
    natoms_upper_limit:
      dpa3_250211_v3_0_0_7M: 850
torsionnet:
  test_data: /bohr/lambench-torsionnet-e4sc/v3/torsionnet500_ccsdt
  calculator_params: null
neb:
  test_data: /bohr/lambench-neb-b1ln/v1/OC20NEB-OOD
  calculator_params: null
wiggle150:
  test_data: /bohr/lambench-wiggle150-yazy/v1/Wiggle150.traj
  calculator_params: null
elastic:
  test_data: /bohr/lambench-elastic-9qdt/v1/elastic.json
  calculator_params:
    fmax: 0.001
    max_steps: 500
vacancy:
  test_data: /bohr/lambench-vacancy-a2xo/v1
  calculator_params: null
binding_energy:
  test_data: /bohr/lambench-binding-dlc6/v1/PLF547
  calculator_params: null
rxn_barrier:
  test_data: /bohr/lambench-BH876-uplk/v1/BH876
  calculator_params: null
pressure:
  test_data: /bohr/lambench-pressure-arjy/v1
  calculator_params:
    fmax: 0.001
    max_steps: 500
stacking_fault:
  test_data: /bohr/lambench-stacking-fault-dtjt/v1
  calculator_params: null
interface:
  test_data: /bohr/lambench-interface-1ric/v1/Interfaces
  calculator_params: null
