AQM:
  test_data:
    PBE: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/AQM_PBE"
    wB97: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/AQM_wB97"
H_nature_2022:
  test_data: 
    PBE: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/H2combustion_PBE"
    wB97: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/H2combustion_wB97"
AIMD_Chig:
  test_data: 
    PBE: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/AIMDChig_PBE"
    wB97: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/AIMDChig_wB97"
HEA25_S:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/HEA25S"
HEA25_bulk:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/HEA25"
MoS2:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/MoS2"
CompressBi:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/CompressBi"
  dispersion_correction: d3zero
NequIP_NC_2022:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/NequIP_NC_2022"
Ca_batteries_CM2021:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/Ca_batteries"
Si_ZEO22:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/Si_ZEO22"
  dispersion_correction: d3bj
REANN_CO2_Ni100:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/REANN_CO2_Ni100"
Cu_MgO_catalysts:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/Cu_MgO_CO2"
  dispersion_correction: d3zero
HPt_NC_2022:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/HPt_NC2022"
Carbon_growth:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/carbon_film_growth"
In2O3_CO2:
  test_data: "/bohr/lambench-ood-zwtr/v5/LAMBench-TestData-v4/In2O3_CO2"
